---
- name: copy tar of the host
  copy:
    src: "{{playbook_dir}}/worker.tar"
    dest: /etc/bin/

- name: copy the service file of the host
  copy:
    src: "{{playbook_dir}}/roles/worker/files/worker.service"
    dest: /etc/systemd/system/


- name: unarhive the file
  unarchive:
    src: /etc/bin/worker.tar
    dest: /etc/bin/
    remote_src: yes

# - name: install java
#   get_url:
#     url: http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jre-8u60-linux-x64.rpm
#     dest: /opt/jre-8u60-linux-x64.rpm
#     headers: 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'

# - name: install Java JRE rpm from a local file
#   yum:
#     name: /opt/jre-8u60-linux-x64.rpm
#     state: present

# - name: Download Java JDK
#   get_url:
#     url: http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64.rpm
#     dest: /opt/jdk-8u60-linux-x64.rpm
#     headers: 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'

# - name: Install Java JDK rpm from a local file
#   yum:
#     name: /opt/jdk-8u60-linux-x64.rpm
#     state: present

# install maven
- name: install maven (and other packages if needed)
  become: yes
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - maven

- name: mvn dependency resolve
  shell: mvn dependency:resolve
  args:
    chdir: /etc/bin/worker/

- name: mvn package.
  shell: mvn package
  args:
    chdir: /etc/bin/worker/
  
- name: Make sure a service is running
  systemd:
    state: started
    name: worker.service
