- name: install system updates for debian systems
  apt: upgrade=dist update_cache=yes
  # when: ansible_distribution == "Debian"

- name: Install base packages
  apt: 
    name: ['apt-transport-https', 'ca-certificates', 'emacs-nox', 'git', 'curl', 'unzip', 'zsh','python3-pip','python3-dev'] 
    state: present
    update_cache: yes
  tags:
    - packages

- name: uploading bootstrap systemd.service to remote host servers
  copy:
    src: "{{playbook_dir}}/source/boot.service"
    dest: /etc/systemd/system/my-awesome-app.service
    owner: root
    group: root
    mode: 0777

- name: install systemd.service unit file
  template: 
    src: "{{playbook_dir}}/source/boot.service"
    dest: /etc/systemd/system/myservice.service

- name: start systemd.service
  systemd: state=started name=myservice daemon_reload=yes

- name: Make sure a serviced.service is running
  systemd:
    state: started
    name: my-awesome-app

######

- name: Template a j2 file to server
  template:
    src: "{{playbook_dir}}/roles/base/source/boot.j2"
    dest: /etc/bin/
    owner: root
    group: root
    mode: '0777'

- name: start systemd.service
  systemd: 
    state: started 
    name: my-awesome-app
    daemon_reload: yes